<?php
//PLEASE FILL IN YOUR DATABASE WHERE YOUR WANT TO MAKE A SKELET OF
define ("dbname","databasename");
define ("dbcharset","utf-8");
define("dbuser","root");
define("dbpass","password");
define("dbhost","localhost");

//PLEASE choose directory to create file in 
//define ("dir","//");


class mysqlskelet
{
	
	public $fields;
	public $tabels;
	public $handle;

	public function create_skelet()
	{



	try {
	$db = new PDO("mysql:host=".dbhost.";dbname=".dbname.";charset=".dbcharset,dbuser,dbpass,array(PDO::ATTR_EMULATE_PREPARES => false,PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));

	$k = 0;
	foreach ($db->query('SHOW TABLES') as $row) //get the different tables in the database
	{
	 $this->tabels[$k] = $row[0];
	 $k++; 
	}//end of fetching tables

	//For each table in the db create the skelet and retriev the fields
	 for ($t=0;$t<(count($this->tabels));$t++)
	 {

	 //create the first-line of our skelet
	 $k = 0;
	 $i = 0;
	 $file = $this->tabels[$t]."-skelet.php";
	 $this->handle = fopen($file, "w");
	 $line1 = "<?php\n//Generated by MysqlSkelet on ".date('Y-m-d h:i:s ',time())." \n//StartMysqlSkelet
 	 \nclass ".$this->tabels[$t]."Skelet {\n";
	 fwrite($this->handle,$line1);
		

	//place the fields in our class as members of the class
		$sql = "SHOW FIELDS FROM ".$this->tabels[$t].";";
	foreach($db->query($sql) as $row)
	 {
	 			
	 		$this->fields[$t][$k] = $row[0];
	 		$line = "\tpublic $".$row[0].";\t//".$row[1]."\n";
	 		
	 		fwrite($this->handle,$line); 
  			$k++;
	
	 }
	 
	 
	}

} catch(PDOException $ex)
{
	echo "An error Occured :". $ex->getMessage();
}
}


public function end_of_file()
{
	fwrite($this->handle,"}");
	 $endingline = "\n//StopMysqlSkelet\n?>";
	 fwrite($this->handle,$endingline);
	 fclose($this->handle);

	

}
}


$test = new mysqlskelet();
$test->create_skelet();
$test->end_of_file();
?>


